version: '2'
services:

######################################
####  DB DATA
######################################
 db_data_mysql:
    image: busybox
    volumes:
    - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw

######################################
####  Zabbix Mysql Server
######################################
 mysql-server:
  image: mysql:5.7
  depends_on:
    - db_data_mysql
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
  expose:
    - "3306"
  volumes_from:
    - db_data_mysql
  volume_driver: local
  env_file:
   - .env_db_mysql
  user: root
  networks:
   zbx_net:

######################################
####  Zabbix Server
######################################
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-3.4-latest
  depends_on:
   - mysql-server
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:rw
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:rw
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:rw
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:rw
  links:
   - mysql-server:mysql-server
  env_file:
   - .env_db_mysql
  user: root
  networks:
   zbx_net:

######################################
####  Zabbix WEB FRONT NGINX
######################################
 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest
  depends_on:
   - zabbix-server
  ports:
   - "8080:80"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  mem_limit: 512m
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
  environment:
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
   - MYSQL_ROOT_PASSWORD=root_pwd
   - MYSQL_DATABASE=zabbix
  env_file:
   - .env_db_mysql
  user: root
  networks:
   zbx_net:

######################################
####  PHPMYADMIN
######################################
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - "8081:80"
  links:
  - mysql-server:mysql-server
  environment:
    - PMA_HOST=mysql-server
    - PMA_PORT=3306
    - PMA_USER=zabbix
    - PMA_PASSWORD=zabbix
  networks:
   zbx_net:

######################################
####  Zabbix Network
######################################
networks:
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
