version: '2'
services:
  mysql-server:
    image: mysql
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    depends_on:
      - mysql-server
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      -  mysql-server
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro

    environment:
       - DB_SERVER_HOST=mysql-server
       - ZBX_SERVER_HOST=zabbix-server-mysql
       - MYSQL_USER=zabbix
       - MYSQL_PASSWORD=zabbix
       - MYSQL_DATABASE=zabbix
       - TZ=America/Sao_Paulo
       - COMPOSE_HTTP_TIMEOUT=200
    links:
      - mysql-server
      - zabbix-server-mysql
    ports:
           - 80:80
volumes:
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
