version: '2'
services:
  jenkins-lts:
    image: jenkins/jenkins:lts
    container_name: Jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    network_mode: "bridge"
